#!/usr/bin/env python3

import os
import sys
import subprocess
import json
from pathlib import Path

# Paths
CONFIG_DIR = Path.home() / ".config"
CACHE_DIR = Path.home() / ".cache"
COLORS_CONF = CONFIG_DIR / "hypr/themes/colors.conf"
COLORS_CSS_DIR = CONFIG_DIR / "waybar/style"
COLORS_CSS = COLORS_CSS_DIR / "colors.css"
SWAYNC_CSS = CONFIG_DIR / "swaync/colors.css"
WAL_CACHE = CACHE_DIR / "wal/colors.json"

def run_wal(image_path):
    print(f"🎨 Running pywal for: {image_path}")
    try:
        # Run wal without setting terminal colors (-n) and without setting wallpaper (-s)
        # We handle those ourselves or via swww
        subprocess.run(["wal", "-i", str(image_path), "-n", "-q"], check=True)
        
        if WAL_CACHE.exists():
            with open(WAL_CACHE) as f:
                return json.load(f)
    except Exception as e:
        print(f"❌ Pywal failed: {e}")
        return None

def update_hypr_colors(colors):
    # Pywal colors are in colors['colors']['colorX']
    # Let's use color1 (usually a nice accent) for the border
    accent = colors["colors"]["color1"]
    c1 = accent.replace("#", "") + "ee"
    
    content = f"""# Dynamic Hyprland Colors (Generated by Pywal)
general {{
    col.active_border = rgba({c1})
    col.inactive_border = rgba(1a1b26aa)
}}

group {{
    col.border_active = rgba({c1})
    col.border_inactive = rgba(1a1b26aa)
}}
"""
    COLORS_CONF.write_text(content)
    subprocess.run(["hyprctl", "reload"])

def update_css_colors(colors):
    # Generate CSS variables from pywal colors
    c = colors["colors"]
    special = colors["special"]
    
    css_content = f"""/* Dynamic Colors Generated by Pywal */
@define-color background {special['background']};
@define-color foreground {special['foreground']};
@define-color cursor {special['cursor']};
@define-color primary {c['color1']};
@define-color accent {c['color2']};

/* Role-based mapping */
@define-color red {c['color1']};
@define-color green {c['color2']};
@define-color yellow {c['color3']};
@define-color blue {c['color4']};
@define-color magenta {c['color5']};
@define-color cyan {c['color6']};
@define-color white {c['color7']};
@define-color gray {c['color8']};
"""
    # Add all 16 colors
    for i in range(16):
        css_content += f"@define-color color{i} {c[f'color{i}']};\n"

    COLORS_CSS_DIR = Path.home() / ".config/waybar/style"
    COLORS_CSS_DIR.mkdir(parents=True, exist_ok=True)
    COLORS_CSS = COLORS_CSS_DIR / "colors.css"
    COLORS_CSS.write_text(css_content)
    
    SWAYNC_CSS.parent.mkdir(parents=True, exist_ok=True)
    SWAYNC_CSS.write_text(css_content)
    
    # Reload components
    subprocess.run(["pkill", "-SIGUSR2", "waybar"])
    subprocess.run(["swaync-client", "-rs"])

def main():
    if len(sys.argv) < 2:
        print("Usage: generate_colors.py <image_path>")
        sys.exit(1)
        
    image_path = Path(sys.argv[1])
    if not image_path.exists():
        print(f"❌ Image not found: {image_path}")
        sys.exit(1)
        
    colors = run_wal(image_path)
    if colors:
        update_hypr_colors(colors)
        update_css_colors(colors)
        print("✅ System colors updated successfully via Pywal!")

if __name__ == "__main__":
    main()
