#!/usr/bin/env python3

import os
import sys
import subprocess
from pathlib import Path
from PIL import Image

# Paths
CONFIG_DIR = Path.home() / ".config"
COLORS_CONF = CONFIG_DIR / "hypr/themes/colors.conf"
COLORS_CSS_DIR = CONFIG_DIR / "waybar/style"
COLORS_CSS = COLORS_CSS_DIR / "colors.css"
SWAYNC_CSS = CONFIG_DIR / "swaync/colors.css"

def get_dominant_color(image_path):
    print(f"🎨 Extracting colors from: {image_path}")
    try:
        with Image.open(image_path) as img:
            img = img.convert("RGB")
            # Resize to 1x1 to get average color
            img = img.resize((1, 1), resample=Image.Resampling.LANCZOS)
            r, g, b = img.getpixel((0, 0))
            return f"#{r:02x}{g:02x}{b:02x}"
    except Exception as e:
        print(f"❌ Color extraction failed: {e}")
        return "#89b4fa" # Fallback Blue

def update_configs(hex_color):
    # Prepare colors
    c1 = hex_color.replace("#", "") + "ee"
    
    # Update Hyprland colors.conf
    hypr_content = f"""# Dynamic Hyprland Colors (Generated by Python PIL)
general {{
    col.active_border = rgba({c1})
    col.inactive_border = rgba(585b70aa)
}}

group {{
    col.border_active = rgba({c1})
    col.border_inactive = rgba(585b70aa)
}}
"""
    COLORS_CONF.write_text(hypr_content)
    subprocess.run(["hyprctl", "reload"])

    # Update CSS Variables
    # We use some hardcoded surface/accent logic for the demo
    css_content = f"""/* Dynamic Colors Generated by Python PIL */
@define-color primary {hex_color};
@define-color background #1e1e2e;
@define-color foreground #cdd6f4;
@define-color accent {hex_color};
"""
    COLORS_CSS_DIR.mkdir(parents=True, exist_ok=True)
    COLORS_CSS.write_text(css_content)
    
    SWAYNC_CSS.parent.mkdir(parents=True, exist_ok=True)
    SWAYNC_CSS.write_text(css_content)
    
    # Reload components
    subprocess.run(["pkill", "-SIGUSR2", "waybar"])
    subprocess.run(["swaync-client", "-rs"])

def main():
    if len(sys.argv) < 2:
        print("Usage: generate_colors.py <image_path>")
        sys.exit(1)
        
    image_path = Path(sys.argv[1])
    if not image_path.exists():
        print(f"❌ Image not found: {image_path}")
        sys.exit(1)
        
    color = get_dominant_color(image_path)
    update_configs(color)
    print(f"✅ System colors updated to: {color}")

if __name__ == "__main__":
    main()
