#!/usr/bin/env python3

import json
import argparse
import sys
from pathlib import Path
import nami_core as core

def run_wal(image_path, mode):
    print(f"🎨 Running pywal ({mode}) for: {image_path}")
    
    # -l flag for light mode
    cmd = ["wal", "-i", str(image_path), "-n", "-q"]
    if mode == "light":
        cmd.append("-l")
        
    core.run_command(cmd, timeout=10)
    
    if core.WAL_CACHE.exists():
        with open(core.WAL_CACHE) as f:
            return json.load(f)
    return None

def update_hypr_colors(colors):
    # Pywal colors are in colors['colors']['colorX']
    # Let's use color1 (usually a nice accent) for the border
    accent = colors["colors"]["color1"]
    c1 = accent.replace("#", "") + "ee"
    
    content = f"""# Dynamic Hyprland Colors (Generated by Pywal)
general {{
    col.active_border = rgba({c1})
    col.inactive_border = rgba(1a1b26aa)
}}

group {{
    col.border_active = rgba({c1})
    col.border_inactive = rgba(1a1b26aa)
}}
"""
    core.ensure_dir(core.HYPR_COLORS_CONF)
    core.HYPR_COLORS_CONF.write_text(content)
    core.run_command(["hyprctl", "reload"], check=False)

def update_css_colors(colors):
    # Generate CSS variables from pywal colors
    c = colors["colors"]
    special = colors["special"]
    
    css_content = f"""/* Dynamic Colors Generated by Pywal */
@define-color background {special['background']};
@define-color foreground {special['foreground']};
@define-color cursor {special['cursor']};
@define-color primary {c['color1']};
@define-color accent {c['color2']};

/* Role-based mapping */
@define-color red {c['color1']};
@define-color green {c['color2']};
@define-color yellow {c['color3']};
@define-color blue {c['color4']};
@define-color magenta {c['color5']};
@define-color cyan {c['color6']};
@define-color white {c['color7']};
@define-color gray {c['color8']};
"""
    # Add all 16 colors
    for i in range(16):
        css_content += f"@define-color color{i} {c[f'color{i}']};\n"

    for path in [core.WAYBAR_COLORS, core.SWAYNC_COLORS]:
        core.ensure_dir(path)
        path.write_text(css_content)
    
    # Reload components
    core.run_command(["pkill", "-SIGUSR2", "waybar"], check=False)
    core.run_command(["swaync-client", "-rs"], check=False)

def update_rofi_colors(colors):
    c = colors["colors"]
    special = colors["special"]
    
    # Generate Rofi rasi content
    rasi_content = f"""* {{
    background:     {special['background']}CC;
    background-alt: {special['background']};
    foreground:     {special['foreground']};
    selected:       {c['color1']}EE;
    active:         {c['color2']};
    urgent:         {c['color3']};
}}
"""
    core.ensure_dir(core.ROFI_PYWAL_COLORS)
    core.ROFI_PYWAL_COLORS.write_text(rasi_content)

def update_zed_colors(colors):
    c = colors["colors"]
    special = colors["special"]
    
    # We create two themes in one file: namipywal_dark and namipywal_light
    # Since pywal is usually dark-focused, we'll map the main ones to dark
    # and maybe do some basic inversion for light if needed, but for now 
    # let's just create the dark one as requested.
    
    def get_zed_style(is_light=False):
        return {
            "background": special['background'],
            "editor.background": special['background'],
            "editor.foreground": special['foreground'],
            "editor.line_number": c['color8'],
            "editor.active_line_number": special['foreground'],
            "terminal.background": special['background'],
            "terminal.foreground": special['foreground'],
            "syntax": {
                "keyword": {"color": c['color1']},
                "function": {"color": c['color2']},
                "string": {"color": c['color3']},
                "number": {"color": c['color4']},
                "type": {"color": c['color5']},
                "comment": {"color": c['color8']},
                "variable": {"color": special['foreground']}
            }
        }

    zed_theme = {
        "$schema": "https://zed.dev/schema/themes/v0.1.0.json",
        "name": "NamiPywal",
        "author": "Antigravity",
        "themes": [
            {
                "name": "namipywal_dark",
                "appearance": "dark",
                "style": get_zed_style()
            },
            {
                "name": "namipywal_light",
                "appearance": "light",
                "style": get_zed_style(is_light=True)
            }
        ]
    }
    
    zed_file = core.ZED_THEMES_DIR / "namipywal.json"
    core.ensure_dir(zed_file)
    zed_file.write_text(json.dumps(zed_theme, indent=4))

def generate_all(image_path, mode="dark"):
    """Main generation entry point for other scripts"""
    image_path = Path(image_path)
    if not image_path.exists():
        print(f"❌ Image not found: {image_path}")
        return False
        
    colors = run_wal(image_path, mode)
    if colors:
        update_hypr_colors(colors)
        update_css_colors(colors)
        update_rofi_colors(colors)
        update_zed_colors(colors)
        print("✅ System colors updated successfully via Pywal!")
        return True
    return False

def main():
    parser = argparse.ArgumentParser(description="Pywal Color Generator")
    parser.add_argument("image", help="Path to the wallpaper image")
    parser.add_argument("--mode", choices=["light", "dark"], default="dark", help="Theme mode")
    args = parser.parse_args()
    
    if generate_all(args.image, args.mode):
        sys.exit(0)
    else:
        sys.exit(1)

if __name__ == "__main__":
    main()
