# Kitty Base Configuration
font_family      Maple Mono
font_size        12.0
bold_font        auto
italic_font      auto
bold_italic_font auto

# Transparency
background_opacity 1.0

# Window padding
window_padding_width 10

# Include theme
include theme.conf
