############################
#       WINDOW RULES        #
############################

# --- Floats ---
windowrule = match:class ^(pavucontrol)$, float 1, size 800 500, center 1
windowrule = match:class ^(nm-connection-editor)$, float 1, size 700 450, center 1
windowrule = match:class ^(blueman-manager)$, float 1, size 800 500, center 1
windowrule = match:class ^(waypaper)$, float 1, size 850 600, center 1

windowrule = match:class ^(org.gnome.Calculator)$, float 1
windowrule = match:class ^(file-roller)$, float 1
windowrule = match:class ^(org.kde.ark)$, float 1

# File pickers / xdg portals
windowrule = match:class ^(xdg-desktop-portal-gtk)$, float 1
windowrule = match:title ^(Open File)$, float 1
windowrule = match:title ^(Save File)$, float 1
windowrule = match:title ^(Choose Files)$, float 1

# Authentication / polkit
windowrule = match:class ^(polkit-gnome-authentication-agent-1)$, float 1
windowrule = match:class ^(hyprpolkitagent)$, float 1

# Picture-in-Picture
windowrule = match:title ^(Picture-in-Picture)$, float 1, pin 1, keep_aspect_ratio 1

# --- Workspace assignments ---
windowrule = match:class ^(ghostty)$, workspace 1
windowrule = match:class ^(firefox)$, workspace 2
windowrule = match:class ^(thunar)$, workspace 3
windowrule = match:class ^(vlc)$, workspace 4
windowrule = match:class ^(discord)$, workspace 5
windowrule = match:class ^(spotify)$, workspace 6


# --- Idle inhibit ---
windowrule = match:class ^(ghostty)$, idle_inhibit focus
windowrule = match:class ^(firefox)$, idle_inhibit fullscreen

# --- Visual fixes ---
windowrule = match:class ^(.*)$, no_shadow 1
windowrule = match:class ^(.*)$, suppress_event maximize
windowrule = match:xwayland 1, rounding 0



# --- Tearing (per-window immediate rules) ---
# windowrule = match:class ^(cs2)$, immediate
# windowrule = match:class ^(steam_app_.*)$, immediate
# windowrule = match:class ^(gamescope)$, immediate




