# vim:ft=kitty

## name:     Gruvbox-Dark
## author:   Converted from Catppuccin-Mocha
## license:  MIT
## blurb:    Gruvbox dark theme for Kitty

# The basic colors
foreground              #EBDBB2
background              #282828
selection_foreground    #282828
selection_background    #FABD2F

# Cursor colors
cursor                  #FABD2F
cursor_text_color       #282828

# URL underline color when hovering with mouse
url_color               #FABD2F

# Kitty window border colors
active_border_color     #FB4934
inactive_border_color   #665C54
bell_border_color       #FB4934

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #282828
active_tab_background   #FB4934
inactive_tab_foreground #EBDBB2
inactive_tab_background #3C3836
tab_bar_background      #282828

# Colors for marks (marked text in the terminal)
mark1_foreground #282828
mark1_background #FB4934
mark2_foreground #282828
mark2_background #B8BB26
mark3_foreground #282828
mark3_background #83A598

# The 16 terminal colors

# black
color0  #282828
color8  #665C54

# red
color1  #FB4934
color9  #FB4934

# green
color2  #B8BB26
color10 #B8BB26

# yellow
color3  #FABD2F
color11 #FABD2F

# blue
color4  #83A598
color12 #83A598

# magenta
color5  #D3869B
color13 #D3869B

# cyan
color6  #8EC07C
color14 #8EC07C

# white
color7  #EBDBB2
color15 #FBF1C7
