[Colloid-Light-catppuccin]
# Spicetify
text               = 4c4f69
subtext            = 5c5f77
main               = eff1f5
main-elevated      = ccd0da
highlight          = dddee5
highlight-elevated = bcc0cc
sidebar            = e6e9ef
player             = eff1f5
card               = ccd0da
shadow             = ccd0da
selected-row       = 7c7f93
button             = 8c8fa1
button-active      = 7c7f93
button-disabled    = 9ca0b0
tab-active         = ccd0da
notification       = ccd0da
notification-error = d20f39
equalizer          = 7c7f93
misc               = bcc0cc


[Colloid-Dark-catppuccin]
# Spicetify
text               = cdd6f4
subtext            = bac2de
main               = 11111b
main-elevated      = 313244
highlight          = 313244
highlight-elevated = 45475a
sidebar            = 11111b
player             = 11111b
card               = 313244
shadow             = 181825
selected-row       = 9399b2
button             = 7f849c
button-active      = 9399b2
button-disabled    = 6c7086
tab-active         = 313244
notification       = 313244
notification-error = f38ba8
equalizer          = 9399b2
misc               = 45475a


[Colloid-Light-nightFox]
# Spicetify
text               = 3b4261
subtext            = 4f577a
main               = f3f4f8
main-elevated      = d6d8e1
highlight          = d6d8e1
highlight-elevated = a0a1bd
sidebar            = e4e6ed
player             = f3f4f8
card               = d6d8e1
shadow             = c8cad5
selected-row       = 5a4fcf
button             = 719cd6
button-active      = 5a4fcf
button-disabled    = a0a1bd
tab-active         = d6d8e1
notification       = d6d8e1
notification-error = c94f6d
equalizer          = 5a4fcf
misc               = a0a1bd


[Colloid-Dark-nightFox]
# Spicetify
text               = cdcecf
subtext            = aeb1b7
main               = 192330
main-elevated      = 283347
highlight          = 283347
highlight-elevated = 575860
sidebar            = 131a24
player             = 192330
card               = 283347
shadow             = 0f1419
selected-row       = 9d79d6
button             = 719cd6
button-active      = 9d79d6
button-disabled    = 575860
tab-active         = 283347
notification       = 283347
notification-error = c94f6d
equalizer          = 9d79d6
misc               = 575860


[Colloid-Light-gruvBox]
# Spicetify
text               = 3c3836
subtext            = 504945
main               = fbf1c7
main-elevated      = ebdbb2
highlight          = ebdbb2
highlight-elevated = d5c4a1
sidebar            = f2e5bc
player             = fbf1c7
card               = ebdbb2
shadow             = d5c4a1
selected-row       = d65d0e
button             = 458588
button-active      = d65d0e
button-disabled    = a89984
tab-active         = ebdbb2
notification       = ebdbb2
notification-error = cc241d
equalizer          = d65d0e
misc               = d5c4a1


[Colloid-Dark-gruvBox]
# Spicetify
text               = ebdbb2
subtext            = d5c4a1
main               = 282828
main-elevated      = 3c3836
highlight          = 3c3836
highlight-elevated = 504945
sidebar            = 1d2021
player             = 282828
card               = 3c3836
shadow             = 1d2021
selected-row       = fe8019
button             = 83a598
button-active      = fe8019
button-disabled    = 7c6f64
tab-active         = 3c3836
notification       = 3c3836
notification-error = fb4934
equalizer          = fe8019
misc               = 504945
